package db_model

// Code generated by xo. DO NOT EDIT.

// SchemaMigration represents a row from 'mydb.schema_migrations'.
type SchemaMigration struct {
	Version string `json:"version"` // version
}
