package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Todo represents a row from 'mydb.todos'.
type Todo struct {
	ID     string       `json:"id"`      // id
	UserID string       `json:"user_id"` // user_id
	Text   string       `json:"text"`    // text
	Done   sql.NullBool `json:"done"`    // done
}
